import servicesReducer from "../reducers/services";

export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD"
export const SEARCH_SKILLS_REQUEST = "SEARCH_SKILLS_REQUEST"
export const SEARCH_SKILLS_FAILURE = "SEARCH_SKILLS_FAILURE"
export const SEARCH_SKILLS_SUCCESS = "SEARCH_SKILLS_SUCCESS"

export const GET_SERVICES = "GET_SERVICES"
export const SERVICES_REQUEST = "SERVICES_REQUEST"
export const SERVICES_FAILURE = "SERVICES_FAILURE"
export const SERVICES_SUCCESS = "SERVICES_SUCCESS"
export const SERVICES_DETAIL = "SERVICES_DETAIL"
export const CHANGE_ID_SERVICE = "CHANGE_ID_SERVICE"
